name: BTC Alert

on:
  schedule:
    - cron: '0,15,30,45 * * * *'  # a cada 15 minutos
  workflow_dispatch: {}           # permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run BTC Alert
        run: python main.py
